FROM hello-world
# Or FROM Instruction is a parent Image from which you are build this new image

RUN echo "we are running some # of cool things"
RUN echo hello \
# whitespace in instruction arguments, such as the commands following RUN, are preserved, so the following example prints hello world with leading whitespace as specified:
RUN echo "\
    hello\
    world"