version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongodb
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27018:27017
    volumes: # using defined volumes to store the replication of data on local storage
      - mongo-data:/data/db
      # the default path where mongodb stores it's data is in '/data/db'
      # For mysql: var/lib/mysql
      # For postgres: var/lib/postgresql/data
      # You can file all the path online where every database store it's data
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    # restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - 8081:8081
# Define the volumes that we will going to use
volumes:
  mongo-data: # name of the volume
    # we have to provide the driver which is the actual storage path and for now we will provide 'local'
    driver: local # 'local' for local file system