FROM hello-world

# The WORKDIR instruction can be used multiple times in a Dockerfile. If a relative path is provided, it will be relative to the path of the previous WORKDIR instruction. For example:
WORKDIR /a
WORKDIR b
WORKDIR c
RUN pwd
# The output of the final 'pwd' command in this Dockerfile would be '/a/b/c'.

# The 'WORKDIR' instruction can resolve environment variables previously set using 'ENV'. You can only use environment variables explicitly set in the Dockerfile. For example:
ENV DIRPATH=/path
WORKDIR $DIRPATH/$DIRNAME
RUN pwd
# The output of the final 'pwd' command in this Dockerfile would be '/path/$DIRNAME'
# If not specified, the default working directory is '/''. In practice, if you aren't building a Dockerfile from scratch (FROM scratch), the 'WORKDIR' may likely be set by the base image you're using.
# Therefore, to avoid unintended operations in unknown directories, it is best practice to set your 'WORKDIR' explicitly.