# Following is the Dockerfile for Nodejs, Mongo, Mongo-Express and Express project that will interact with MongoDB
# the project is already done in '../07_Demo_Project'
FROM node
# Start by basing it on another image which is the environment
# Because we are running the javascript application on nodejs backend so we need a node js environment to run the javascript
# where it fetch the image from: https://hub.docker.com/_/node
ENV MONGO_DB_USERNAME=admin
